export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_REQUEST_SUCCESS = 'EMPLOYEE_LIST_REQUEST_SUCCESS';

export const EMPLOYEE_LIST_DELETE_REQUEST = "EMPLOYEE_LIST_DELETE_REQUEST";
export const EMPLOYEE_LIST_DELETE_REQUEST_SUCCESS = "EMPLOYEE_LIST_DELETE_REQUEST_SUCCESS" 