export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_REQUEST_SUCCESS = 'EMPLOYEE_LIST_REQUEST_SUCCESS';

export const EMPLOYEE_LIST_DELETE_REQUEST = "EMPLOYEE_LIST_DELETE_REQUEST";
export const EMPLOYEE_LIST_DELETE_REQUEST_SUCCESS = "EMPLOYEE_LIST_DELETE_REQUEST_SUCCESS" 

export const ADD_NEW_EMPLOYEE_REQUEST = "ADD_NEW_EMPLOYEE_REQUEST";
export const ADD_NEW_EMPLOYEE_REQUEST_SUCCESS = "ADD_NEW_EMPLOYEE_REQUEST_SUCCESS";


